### ISSUE TITLE
issue inputting location

### ISSUE THREAD

**Issue by JTyler70** [OfficeDev/microsoft-teams-emergency-operations-center#178]
I can't create a new incident because nothing will save under location. All of the other fields seem to work fine.

**Comment by v-ajaysahu** [comment]
@JTyler70 , Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network traces which will help us to troubleshoot the issue.
Also request you to share the manifest files with us also share the Graph permissions.

**Comment by JTyler70** [comment]
Here's the console log:
v2/:1 [ExpLoader] Getting things ready...
v2/:1  [ExpLoader] ExperienceLoader: [T2->T1 auto-redirection] loading T2 - user is opted into T2 web
warn @ v2/:1
v2/:1  [ExpLoader] ExperienceLoader: [RecordWebBootAttempt] not recording T2 web boot attempt - boot attempt occurred too soon. TimeSinceLastBootAttempt=4026ms
warn @ v2/:1
v2/:1 [Auth]: auth_cache initialized
v2/:1 [Auth]: authTelemetryProvider initialized
v2/:1 [Auth]: [Telemetry][cf5afd31-2408-4035-803f-90e1f0197cc5][auth_web_initialization] [start] - telemetry provider created for createAuthenticationServiceInstance, source: core-auth-tasks::init with shouldCreateScenario: [true]
manifest.json:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
manifest.json:1  Manifest: Line: 1, column: 1, Syntax error.
precompiled-web-worker-645c0de537598acd.js:1 [Auth]: authTelemetryProvider initialized
v2/:1  message handler already registered for - pulsarSignal
warn @ v2/:1
2precompiled-web-worker-645c0de537598acd.js:1  Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - groupsServiceV2 is missing in discover response
    at l (precompiled-web-worker-645c0de537598acd.js:1:3633735)
    at precompiled-web-worker-645c0de537598acd.js:1:7517230
118Third-party cookie will be blocked. Learn more in the Issues tab.
precompiled-web-worker-645c0de537598acd.js:1  Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
    at https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:2894510
    at En (https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:3310872)
    at Function.<anonymous> (https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:3353624)
    at En (https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:3310925)
    at Function.attempt (https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:3342148)
    at https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:2894475
    at wn (https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:3311162)
    at Function.fr (https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:3346232)
    at https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:2893217
    at En (https://teams.microsoft.com/v2/worker/precompiled-web-worker-645c0de537598acd.js#{%22experienceName%22:%22react-web-client%22,%22ring%22:%22general%22,%22environment%22:%22prod%22,%22sessionId%22:%22c0702e43-fa97-4cd5-a17f-eab19134065b%22,%22platformId%22:1415,%22buildVersion%22:%2224020205514%22,%22localeCode%22:%22en-us%22,%22publicPath%22:%22https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/%22,%22preECSConsoleLogLevel%22:0,%22deviceId%22:%22b943708f-d9b3-49f3-816b-33fef9b6003c%22,%22telemetryWorkerBroadcast%22:true}:1:3310872)
v2/:1  Unhandled error/rejection {"isTrusted":true}
error @ v2/:1
v2/:1  The icon "vNextCancel" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextChat" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCopy" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextPhone" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextDocument" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextEdit" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextEmoji" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextOrg" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextSend" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextVideo" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextChevronDown" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextChevronLeft" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextChevronRight" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextOpen" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextAdd" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextAddFriend" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextAttach" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextBalloons" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCalendar" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCamera" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCheckMark" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCityNext" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextContact" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextContactCard" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextGlobe" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextGroup" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextInfo" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextLink" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextLinkedInLogo" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextPoi" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextMail" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextMore" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextOutOfOffice" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextPage" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextPeople" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextPlannerLogo" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextQuickNote" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextRibbon" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextSearch" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextShare" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextBack" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextClear" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextAccept" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextAccounts" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextBank" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextBirthdayCake" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "Blank" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextBlockContact" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCellPhone" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCityNext2" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextClock" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextCompleted" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextDateTime" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextDelete" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextDeveloperTools" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextDown" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextEmi" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextEmoji2" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextError" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextErrorBadge" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextFax" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextFeedback" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextFeed" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextFlag" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextForward" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextHeart" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextHelp" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextIDBadge" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextImportant" tried to unregister but was not registered.
warn @ v2/:1
v2/:1  The icon "vNextLightbulb" tried to unregister but was not registered.
The network traces:
[teams.microsoft.com.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14483828/teams.microsoft.com.zip)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/161762248/0a36b2ff-500a-4aa9-ab66-b4f85c50de7d)
can you point me to where to get the manifest for you?

**Comment by v-ajaysahu** [comment]
@JTyler70 , Thank you for sharing the details.
As per the permission screenshot which you have shared, we found that Admin Consent has not provided. Could you please provide admin consent in order to work. 
Refer this link - https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#7-add-permissions-for-office-365-exchange-online
Also, please check your version of the app it should be latest version. In order to check the current version of the app please follow the below steps -

- Go to the Teams Admin portal and click on the Manage Apps tab. In the search box, type TEOC and press enter.
Direct Link - https://admin.teams.microsoft.com/policies/manage-apps
- Click on the TEOC app link.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/b132b435-9e0f-48bc-8856-2009d4afda17)
- You will see the Published version number under the app name.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/6858632c-3942-469d-a50b-e3e54387966d)
